# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_head', models.TextField(verbose_name='Aukahlutir \xed HEAD tag')),
                ('text_type', models.CharField(choices=[(b'M', b'Markdown'), (b'H', b'HTML')], max_length=1, verbose_name='Tegund texta')),
                ('page_url', models.SlugField(max_length=64, verbose_name='URL sem s\xed\xf0an \xe1 a\xf0 vera \xe1')),
                ('text', models.TextField()),
                ('menubar', models.CharField(max_length=64, verbose_name='Texti \xed anchor')),
                ('place_in_menubar', models.BooleanField(verbose_name='Setja \xfeessa s\xed\xf0u \xed s\xed\xf0uhaus')),
                ('order_in_menubar', models.IntegerField(db_index=True, unique=True, verbose_name='R\xf6\xf0 \xed s\xed\xf0uhaus')),
            ],
        ),
    ]
