# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='extra_head',
            field=models.TextField(blank=True, null=True, verbose_name='Aukahlutir \xed HEAD tag'),
        ),
    ]
