#!/bin/bash

WORKDIR=$(dirname "$0")/..

NAME="vaa_app"                         # Name of the application
DJANGODIR="$WORKDIR"                   # Django project directory
SOCKFILE="$WORKDIR/run/$NAME.sock"     # we will communicte using this unix socket
USER=$(whoami)                         # the user to run as
GROUP=$(whoami)                        # the group to run as
NUM_WORKERS=4                          # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=vaa.settings    # which settings file should Django use
DJANGO_WSGI_MODULE=vaa.wsgi            # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd "$DJANGODIR"
source env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR="$(dirname "$SOCKFILE")"
test -d "$RUNDIR" || mkdir -p "$RUNDIR"

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize
# themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:"$SOCKFILE"

# --bind=127.0.8.80:8000
