# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160706_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='blurb',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
