# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20160706_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('text', models.TextField()),
                ('mod', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
