# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160707_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='claim_token',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='claimed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
