# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160715_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ends', models.DateTimeField()),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.RunSQL("INSERT INTO questions_election (id, ends, slug) VALUES (1, '12-Aug-2016 00:00:00 GMT','reykjavik2016')"),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Election'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Election'),
            preserve_default=False,
        ),
    ]
