# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20160720_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='claim_token',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='claimed',
        ),
    ]
