# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20160724_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lookup', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lookup', models.CharField(max_length=40)),
            ],
        ),
    ]
